enum ScreenNameEnum {
    
    // Home
    HOME_TAB_SCREEN = 'HOME_TAB_SCREEN',
    DRAWER_NAVIGATION ='DRAWER_NAVIGATION',
    FEATURE_NAVIGATION ='FEATURE_NAVIGATION',
    REGISTER_NAVIGATION ='REGISTER_NAVIGATION',
   

    // auth
    
    WELCOME_SLIDER_SCREEN = "WElCOME_SLIDER_SCREEN",
    LOGIN_SCREEN = 'LOGIN_SCREEEN',
    REGISTER_SCREEN ='REGISTER_SCREEN',
    FORGOT_PASSWORD ='FORGOT-PASSWORD',


    // Drawer
    VCARD_SCREEN = 'VCARDS_SCREEN',
    PROJECT_SCREEN = 'PROJECT_SCREEN',
    PIXELS_SCREEN='PIXELS_SCREEN',
    CUSTOMDOMAIN_SCREEN ='CUSTOMDOMAIN_SCREEN',
    
    //Features
    CREATE_PROJECT ='CREATE_PROJECT',
    CREATE_PIXEL = 'CREATE_PIXEL',
    CONNECT_DOMAIN ='CONNECT_DOMAIN',
    CREATE_VCARD='CREATE_VCARD',
    EDIT_VCARD='EDIT_VCARD'



    
  
  }
  
  export default ScreenNameEnum;
  