enum ScreenNameEnum {

  // Home
  HOME_TAB_SCREEN = 'HOME_TAB_SCREEN',
  DRAWER_NAVIGATION = 'DRAWER_NAVIGATION',
  FEATURE_NAVIGATION = 'FEATURE_NAVIGATION',
  REGISTER_NAVIGATION = 'REGISTER_NAVIGATION',


  // auth

  WELCOME_SLIDER_SCREEN = "WElCOME_SLIDER_SCREEN",
  LOGIN_SCREEN = 'LOGIN_SCREEEN',
  REGISTER_SCREEN = 'REGISTER_SCREEN',
  FORGOT_PASSWORD = 'FORGOT-PASSWORD',


  // Drawer
  VCARD_SCREEN = 'VCARDS_SCREEN',
  PROJECT_SCREEN = 'PROJECT_SCREEN',
  PIXELS_SCREEN = 'PIXELS_SCREEN',
  CUSTOMDOMAIN_SCREEN = 'CUSTOMDOMAIN_SCREEN',
  //STACK_SCREEN
  PIXEL_STACK = 'PIXEL_STACK',
  PROJECT_STACK = 'PROJECT_STACK',
  VCARD_STACK = 'VCARD_STACK',
  ACCOUNT_STACK = 'ACCOUNT_STACK',
  DOMAIN_STACK = 'DOMAIN_STACK',

  //Features
  CREATE_PROJECT = 'CREATE_PROJECT',
  CREATE_PIXEL = 'CREATE_PIXEL',
  CONNECT_DOMAIN = 'CONNECT_DOMAIN',
  CREATE_VCARD = 'CREATE_VCARD',
  EDIT_VCARD = 'EDIT_VCARD',
  ACCOUNT_SCREEN = 'Account_Screen',
  VCARD_QR = 'Vcard_QR',
  Edit_Project = 'Edit_Project',
  Edit_Pixel = 'Edit_Pixel',
  Edit_Domain = 'Edit_Domain'






}

export default ScreenNameEnum;
